"""Auto-generated by Self-Healing Builder."""
from __future__ import annotations

def add(a: float, b: float) -> float:
    """Return sum of a and b."""
    return a + b

def subtract(a: float, b: float) -> float:
    """Return a minus b."""
    return a - b

def multiply(a: float, b: float) -> float:
    """Return product of a and b."""
    return a * b

def divide(a: float, b: float) -> float:
    """Return a divided by b. Raises ValueError on zero division."""
    if b == 0:
        raise ValueError("Cannot divide by zero")
    return a / b

if __name__ == "__main__":
    print(add(2, 3))
    print(divide(10, 2))
