"""Auto-generated by Self-Healing Builder."""
from __future__ import annotations

def is_palindrome(s: str) -> bool:
    """Return True if s is a palindrome (ignores case and non-alphanumeric)."""
    import re
    cleaned = re.sub(r"[^a-z0-9]", "", s.lower())
    return cleaned == cleaned[::-1]

def count_vowels(s: str) -> int:
    """Count vowels in string."""
    return sum(1 for c in s.lower() if c in "aeiou")

if __name__ == "__main__":
    print(is_palindrome("Racecar"))
